PRAGMA user_version = 1;

CREATE TABLE IF NOT EXISTS catalog (
	CatalogId		INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT UNIQUE,
	CatalogName		VARCHAR2 NOT NULL UNIQUE
);

CREATE TABLE IF NOT EXISTS valueType (
	id				INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT UNIQUE,
	code			VARCHAR2 NOT NULL UNIQUE
);

CREATE TABLE IF NOT EXISTS measure (
	id				INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT UNIQUE,
	code			VARCHAR2 NOT NULL UNIQUE,
	code_en			VARCHAR2,
	code_ru			VARCHAR2,
	valueTypeId		INTEGER
);

